service: serverless-carts-service

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-1'
  profile: 'sandx'
  environment: 
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DATABASE: ${env:DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /